[package]
name = "event_logs"
author = "kuzan04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.4"
hex = "0.4.3"
chrono = "0.2.16"
pcap = "1.0.0"
